sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tbuff100/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tbuff100/docker-react npm run test