sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tbuff100/docker-react -f Dockerfile.dev .

script:
  - docker run tbuff100/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-964318651267"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"